#!/usr/bin/env python3
"""Regenerate Table 4, Figure 4, and the manuscript document from whatever
confirmation runs are currently complete. Safe to run repeatedly."""
import json, subprocess, sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent
AR = ROOT / "paper4_pipeline/outputs/autoresearch"
R = AR / "runs"
FIG = ROOT / "paper4_pipeline/outputs/hess_100train_50test_final/figures"
LBL = {"random_forest": "Random Forest", "xgboost": "XGBoost",
       "xlstm": "xLSTM", "transformer": "Transformer"}
# families where no proposal was promoted would use the baseline as selection (none in this campaign)
NO_PROMOTION: set[str] = set()
SPLITS = [("val", "Development validation"), ("test", "Temporal confirmation"),
          ("spatial_test", "Held-out catchments")]


def med(run, model, split, col="kge"):
    f = R / run / "tables" / "metrics_by_basin.csv"
    if not f.exists():
        return None
    m = pd.read_csv(f)
    d = m[(m.model == model) & (m.split == split)]
    return round(float(d[col].median()), 3) if len(d) else None


def table4() -> str:
    """Table 4 now carries paired basin-bootstrap intervals, so it is generated by
    bootstrap_ci.py (which restricts each contrast to catchments valid under both
    configurations). Regenerate it there and reuse the result, so the manuscript
    table and the reported intervals can never drift apart."""
    src = ROOT / "table4_with_ci.md"
    subprocess.run([str(ROOT / "paper4_pipeline/.venv_arm64/bin/python"),
                    str(ROOT / "bootstrap_ci.py")], check=True, capture_output=True)
    return src.read_text().strip()


def figure4() -> list[str]:
    sys.path.insert(0, str(ROOT / "paper4_pipeline/src"))
    import matplotlib.pyplot as plt
    import numpy as np
    from matplotlib.patches import Patch
    from paper4.style import apply_style, MODEL_COLORS, COL_DOUBLE
    apply_style()
    fams = [f for f in LBL if med(f"agent_confirm_baseline_{f}", f, "val") is not None]
    if not fams:
        return []
    fig, ax = plt.subplots(figsize=(COL_DOUBLE, 3.0))
    x = np.arange(len(SPLITS))
    w = 0.8 / len(fams)
    for i, f in enumerate(fams):
        b = [med(f"agent_confirm_baseline_{f}", f, s) for s, _ in SPLITS]
        sel = [b[j] if f in NO_PROMOTION else med(f"agent_confirm_selected_{f}", f, s)
               for j, (s, _) in enumerate(SPLITS)]
        off = (i - (len(fams) - 1) / 2) * w
        ax.bar(x + off - w * 0.2, b, w * 0.4, color=MODEL_COLORS[f], alpha=0.45,
               edgecolor="#1F1F1F", lw=0.3)
        ax.bar(x + off + w * 0.2, sel, w * 0.4, color=MODEL_COLORS[f],
               edgecolor="#1F1F1F", lw=0.3)
        for xi, (bb, ss) in enumerate(zip(b, sel)):
            if bb and ss and abs(ss - bb) > 0.005:
                ax.annotate(f"{ss - bb:+.3f}", (x[xi] + off, max(bb, ss) + 0.012),
                            ha="center", fontsize=5.6, color=MODEL_COLORS[f])
    handles = [Patch(facecolor="#5B6770", alpha=0.45, label="expert baseline"),
               Patch(facecolor="#5B6770", label="agent-selected")]
    handles += [Patch(facecolor=MODEL_COLORS[f], label=LBL[f]) for f in fams]
    ax.legend(handles=handles, fontsize=6, frameon=False, ncol=3, loc="upper right")
    ax.set_xticks(x)
    ax.set_xticklabels([n.replace(" ", "\n") for _, n in SPLITS], fontsize=7)
    ax.set_ylabel("Median KGE")
    ax.set_ylim(0, 0.95)
    ax.grid(True, axis="y", alpha=0.25, lw=0.4)
    fig.tight_layout()
    fig.savefig(FIG / "fig04_confirmation.png", dpi=600, bbox_inches="tight")
    fig.savefig(FIG / "fig04_confirmation.pdf", bbox_inches="tight")
    return fams


def fill_placeholders(text: str) -> str:
    """Replace XLSTM_* markers once the xLSTM confirmation exists."""
    b = {sp: med("agent_confirm_baseline_xlstm", "xlstm", sp) for sp, _ in SPLITS}
    s_ = {sp: med("agent_confirm_selected_xlstm", "xlstm", sp) for sp, _ in SPLITS}
    if any(v is None for v in list(b.values()) + list(s_.values())):
        return text
    d = {k: s_[k] - b[k] for k in b}
    deltas = (f"{d['val']:+.3f} on validation, {d['test']:+.3f} during temporal confirmation, "
              f"and {d['spatial_test']:+.3f} in held-out catchments")
    text = text.replace("XLSTM_DELTAS", deltas)
    text = text.replace("XLSTM_VALGAIN", f"{d['val']:+.3f}")
    return text


def main() -> None:
    fams = figure4()
    print("figure 4 families:", fams)
    new = table4()
    src = ROOT / "agent_paper_manuscript.md"
    s = src.read_text()
    start = s.index("| Family | Domain | Expert baseline KGE |")
    end = s.index("\n\n", start)
    assert "95 % CI" in new, "Table 4 must carry bootstrap intervals"
    s = s[:start] + new + s[end:]
    s = fill_placeholders(s)
    src.write_text(s)
    left = s.count("XLSTM_DELTAS") + s.count("XLSTM_VALGAIN")
    print("unfilled placeholders:", left)
    print("Table 4 updated:")
    print(new)
    subprocess.run([str(ROOT / "paper4_pipeline/.venv_arm64/bin/python"),
                    str(ROOT / "paper/build_agent_paper_docx.py")], check=True)
    subprocess.run(["/Applications/LibreOffice.app/Contents/MacOS/soffice", "--headless",
                    "--norestore", "--convert-to", "pdf", "--outdir", str(ROOT),
                    str(ROOT / "AgentPaper_manuscript_draft.docx")],
                   capture_output=True)
    print("document rebuilt")


if __name__ == "__main__":
    main()
